#!/bin/bash

set -euo pipefail

if [[ ! -f /usr/sbin/tailscaled ]]; then
    echo "Tailscale not installed"
else
    echo "Starting tailscaled"
    tmux new-session -d -s tailscaled 'sudo /usr/sbin/tailscaled --state=mem:'
fi